### ISSUE TITLE
Upload not blocked while a file is already uploading

### ISSUE THREAD

**Issue by aaronpcz** [Artear/ReactResumableJS#19]
Hi,

Is it possible to disable fresh uploads while one is currently being uploaded?

I'll provide a code sample of our component props

```
<ReactResumableJs
       uploaderID="image-upload"
       dropTargetID="media-upload-drop-target"
       filetypes={ALL_FILE_TYPES}
       fileAccept={"*"}
       fileAddedMessage="Started!"
       completedMessage="Complete!"
       service={assetUploadApi}
       query={{token: connectionCache.getToken()}}
       generateUniqueIdentifier={function() { return hat(); }}
       textLabel="Uploaded files"
       previousText="Drop to upload your media:"
       disableDragAndDrop={true}
       onFileSuccess={this.resumableOnFileSuccess}
       onFileAdded={this.resumableOnFileAdded}
       maxFiles={1}
       maxFileSize={1000000000}
       showFileList={false}
></ReactResumableJs>
```

Many thanks,

Aaron

**Comment by alejodaraio** [comment]
Hello !

We can add that feature as an option, its a good point!
Wait please for the next version.

Cheers.

**Comment by alejodaraio** [comment]
Hello :)

New Version:

https://www.npmjs.com/package/react-resumable-js

1.1.19
Now you can pause, cancel or resume the upload
added start button option
added pause button option
added cancel button option
added onStartUpload callback
added onPauseUpload callback
added onCancelUpload callback

**Comment by RejinR** [comment]
@alejodaraio Could you please show a code snippet on how this can be used to block a second upload?
