### ISSUE TITLE
Error when user uploads media created from iOS (upper case extension)

### ISSUE THREAD

**Issue by aaronpcz** [Artear/ReactResumableJS#20]
I would like to raise a potential bug, we are having issues with users who are uploading media created on iOS devices.  As for what ever reason upper case extensions are used, the library seems to have an issue with this use case.

Has anyone else experienced this issue?

Is there a fix, we can put in place?

EDIT: Thinking about it, this might be more suitable to be posted in the resumable js github

Yep this was fixed as of : https://github.com/23/resumable.js/issues/278

Thanks,
Aaron

**Comment by alejodaraio** [comment]
The issue on resumablejs has not been merged on master, they have conflicts https://github.com/23/resumable.js/pull/319

One workaround is put ['mov', **'MOV'**, 'mp4', 'f4v']

**Comment by aaronpcz** [comment]
Cheers, the workaround is fine for now.
