### ISSUE TITLE
Is there a way to force chunkSize?

### ISSUE THREAD

**Issue by natealcedo** [Artear/ReactResumableJS#25]
I was looking at the docs on the resumable.js github and noticed that there is an option to force the size of a chunk. I noticed that there isn't a way to do the same with this component. How do I achieve the same behaviour?

Edit: I read into your source code and realised that it is possible to do force the chunkSize to be a certain size. Maybe this could be a prop on the component which defaults to false. Would you be ok to me doing a pull request to do this?

**Comment by alejodaraio** [comment]
Done, and update :)
